# Generated by Django 5.0.6 on 2024-06-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_case_case_id_alter_user_govt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.case'),
        ),
    ]
